2019-11-27 20:39:36 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/customize.yaml contains duplicate key "switch.wall_switch_left_158d00016c31cf". Check lines 4 and 18.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 366 and 367.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 367 and 368.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 368 and 369.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 369 and 370.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 370 and 371.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 371 and 372.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 372 and 373.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 373 and 374.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 374 and 375.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 375 and 376.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 379 and 380.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/includes/automation/system.yaml contains duplicate key "entity_id". Check lines 380 and 381.
2019-11-27 20:39:38 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "discovery". Check lines 25 and 77.
2019-11-27 20:39:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-27 20:39:50 ERROR (MainThread) [homeassistant.setup] Setup failed for googlehome: Integration not found.
2019-11-27 20:40:02 WARNING (MainThread) [homeassistant.setup] Setup of person is taking over 10 seconds.
2019-11-27 20:40:02 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2019-11-27 20:40:02 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.
2019-11-27 20:40:02 WARNING (MainThread) [homeassistant.setup] Setup of yeelight is taking over 10 seconds.
2019-11-27 20:40:03 ERROR (Thread-8) [plexapi] http://172.104.139.30:8443: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2019-11-27 20:40:04 WARNING (SyncWorker_15) [androidtv.adb_manager] Couldn't connect to host 192.168.1.185:5555, error: Connection refused
2019-11-27 20:40:04 WARNING (SyncWorker_15) [homeassistant.components.androidtv.media_player] Could not connect to Android TV at 192.168.1.185:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'
2019-11-27 20:40:06 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 30 seconds.
2019-11-27 20:40:14 WARNING (MainThread) [homeassistant.components.duckdns] Updating DuckDNS domain failed: http://mothership-home.duckdns.org:8123
2019-11-27 20:40:55 WARNING (SyncWorker_13) [androidtv.adb_manager] Couldn't connect to host 192.168.1.185:5555, error: Connection refused
2019-11-27 20:40:55 WARNING (SyncWorker_13) [homeassistant.components.androidtv.media_player] Could not connect to Android TV at 192.168.1.185:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'
2019-11-27 20:40:55 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 60 seconds.
2019-11-27 20:40:56 WARNING (MainThread) [homeassistant.components.duckdns] Updating DuckDNS domain failed: http://mothership-home.duckdns.org:8123
2019-11-27 20:41:56 WARNING (SyncWorker_11) [androidtv.adb_manager] Couldn't connect to host 192.168.1.185:5555, error: Connection refused
2019-11-27 20:41:56 WARNING (SyncWorker_11) [homeassistant.components.androidtv.media_player] Could not connect to Android TV at 192.168.1.185:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'
2019-11-27 20:41:56 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 90 seconds.
2019-11-27 20:42:37 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.motion_sensor_lights_on. Invalid data for call_service at pos 1: None for dictionary value @ data['rgb_color']
2019-11-27 20:43:27 WARNING (SyncWorker_3) [androidtv.adb_manager] Couldn't connect to host 192.168.1.185:5555, error: Connection refused
2019-11-27 20:43:27 WARNING (SyncWorker_3) [homeassistant.components.androidtv.media_player] Could not connect to Android TV at 192.168.1.185:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'
2019-11-27 20:43:27 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 120 seconds.
2019-11-27 20:45:28 WARNING (SyncWorker_19) [androidtv.adb_manager] Couldn't connect to host 192.168.1.185:5555, error: Connection refused
2019-11-27 20:45:28 WARNING (SyncWorker_19) [homeassistant.components.androidtv.media_player] Could not connect to Android TV at 192.168.1.185:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'
2019-11-27 20:45:28 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 150 seconds.
2019-11-27 20:45:55 WARNING (MainThread) [homeassistant.components.duckdns] Updating DuckDNS domain failed: http://mothership-home.duckdns.org:8123
2019-11-27 20:46:46 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.motion_sensor_lights_on. Invalid data for call_service at pos 1: None for dictionary value @ data['rgb_color']
